namespace Problems.String;

/// <summary>
/// You are given two strings s and t.
/// String t is generated by random shuffling string s and then add one more letter at a random position.
/// Return the letter that was added to t.
/// </summary>

/// <example>
/// Input: s = "abcd", t = "abcde"
/// Output: "e"
/// </example>

public class FindTheDifference
{
    public char SolutionA(string s, string t)
    {
        var hash = new Dictionary<char, int>();
        for (var i = 0; i < s.Length; i++)
        {
            if (hash.ContainsKey(s[i]))
                hash[s[i]]++;
            else
                hash[s[i]] = 1;
        }

        for (var i = 0; i < t.Length; i++)
        {
            if (!hash.ContainsKey(t[i]) || hash[t[i]] == 0)
                return t[i];

            hash[t[i]]--;
        }


        return '0';
    }

    public char SolutionB(string s, string t)
    {
        var tSorted = t.ToArray();
        System.Array.Sort(tSorted);

        var sSorted = s.ToArray();
        System.Array.Sort(sSorted);

        for (var i = 0; i < tSorted.Length; i++)
        {
            if (i + 1 > sSorted.Length || tSorted[i] != sSorted[i])
                return tSorted[i];
        }

        return '0';
    }

    public char SolutionC(string s, string t)
    {
        return (char)(t.Sum(c => c) - s.Sum(c => c));
    }
}